name: OcarinaSong
version: 1.0
description: Provides perks for voting for the server. For Outbreak-Gaming.
author: Jackcrawf3
main: me.jackcrawf3.ocarinasong.OcarinaSong

permissions:
    jack.ocarina:
            default: op
            description: Lets you play the Ocarina!
    jack.ocarina.time:
            default: op
            description: Lets you play the Song of Time wtih effect!
    jack.ocarina.storms:
            default: op
            description: Lets you play the Song of Storms; Change Weather!
    jack.ocarina.healing:
            default: op
            description: Makes it so that playing the Song of Healing will gradually heal you!
commands:
    ocarina:
        description: Checks the list of songs playable on your ocarina!
        aliases: [ocarina, songs]
        usage: /ocarina
