name: OcarinaSong
version: 1.0
description: Provides perks for voting for the server. For Outbreak-Gaming.
author: Jackcrawf3
main: me.jackcrawf3.ocarinasong.OcarinaSong

permissions:
    jack.ocarina:
            default: op
            description: Lets you play the Ocarina!
    jack.ocarina.time:
            default: op
            description: Lets you play the Song of Time wtih effect!
    jack.ocarina.storms:
            default: op
            description: Lets you play the Song of Storms; Change Weather!
    jack.ocarina.healing:
            default: op
            description: Makes it so that playing the Song of Healing will gradually heal you!
    jack.ocarina.healing.wool:
            default: op
            description: Makes it so that playing the Song of Healing will replenish sheep wool!
    jack.ocarina.healing.pig:
            default: op
            description: Makes it so that playing the Song of Healing will heal Pigmen into pigs!
    jack.ocarina.healing.burn:
            default: op
            description: Makes it so that playing the Song of Healing will burn the evil out of mobs!
    jack.ocarina.zeldacalm:
            default: op
            description: Allows you to calm wild animals using Zelda's Lullaby!
    jack.ocarina.zeldatame:
            default: op
            description: Allows you to tame wild animals using Zelda's Lullaby!
commands:
    ocarina:
        description: Checks the list of songs playable on your ocarina!
        aliases: [ocarina, songs]
        usage: /ocarina
